name: openpdd
recipe: wordpress

config:
    via: nginx
    ssl: true
    database: mysql
    config:
        vhosts: storage/provision/nginx/default.conf

proxy:
    appserver_nginx:
        - openpdd.lndo.site
        - buren.openpdd.lndo.site
        - gemeentehw.openpdd.lndo.site
        - ggdhollandsnoorden.openpdd.lndo.site
        - hollandskroon.openpdd.lndo.site
        - sudwestfryslan.openpdd.lndo.site
    mailhog:
        - mail.openpdd.lndo.site
    pma:
        - pma.openpdd.lndo.site

services:
    pma:
        type: phpmyadmin
        ssl: true
        scanner:
          timeout: 1000
          retry: 5
        hosts:
            - database
    mailhog:
        type: mailhog
        portforward: true
        hogfrom:
            - appserver
    appserver:
        type: php:7.4
        build:
            - composer install
        xdebug: true
        webroot: htdocs
        composer_version: 2
        overrides:
            volumes:
                - ~/.lando/composer/auth.json:/var/www/.composer/auth.json
        config:
            php: storage/provision/php/php.ini
            xdebug: 'develop,debug'
    node:
        type: node
        globals:
            webpack: 'latest'
            npm: 'latest'

tooling:
    phpunit:
        service: appserver
    deploy:
        service: appserver
        cmd: ./vendor/bin/dep deploy
    npm:
        service: node
    xdebug-on:
        service: appserver
        description: Enable xdebug for nginx.
        cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm && echo "Enabling xdebug"
        user: root
    xdebug-off:
        service: appserver
        description: CUSTOM Disable xdebug for nginx.
        cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm && echo "Disabling xdebug"
        user: root
