name: owc-forms
recipe: wordpress

config:
  via: nginx
  ssl: true
  database: mysql:5.7
  config:
    vhosts: storage/provision/nginx/default.conf

proxy:
  appserver_nginx:
    - owc-forms.lndo.site
    - buren.owc-forms.lndo.site
    - hw.owc-forms.lndo.site
    - nijmegen.owc-forms.lndo.site
  mailhog:
    - mail.owc-forms.lndo.site
  pma:
    - pma.owc-forms.lndo.site

services:
  pma:
    type: phpmyadmin
    ssl: true
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  appserver:
    type: php:7.4
    build:
      - composer install
    xdebug: false
    webroot: htdocs
    composer_version: 2
    overrides:
      volumes:
        - ~/.lando/composer/auth.json:/var/www/.composer/auth.json
    config:
      php: storage/provision/php/php.ini
  node:
    type: node
    globals:
      webpack: "latest"
      npm: "latest"

tooling:
  npm:
    service: node
  deploy:
    service: appserver
    cmd: ./vendor/bin/dep deploy
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
